[package]
name = "plaid-generate"
publish = false
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.62"
openapi-client-generator = { git = "https://github.com/libninjacom/openapi-client-generator" }
serde_yaml = "0.8.23"

# Use this for local development. Example:
[patch."https://github.com/libninjacom/openapi-client-generator"]
openapi-client-generator = { path = "/Users/kurt/work/openapi-client-generator" }
